enum actionTypeKeys {
  //Login
  LOGIN_REQUEST = 'LOGIN_REQUEST',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT_REQUEST = 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE = 'LOGOUT_FAILURE',
  VERIFY_REQUEST = 'VERIFY_REQUEST',
  VERIFY_SUCCESS = 'VERIFY_SUCCESS',
  RESET_USER = 'RESET_USER',
  //Data
  GET_DATA_PENDING = 'GET_DATA_PENDING',
  GET_DATA_SUCCESS = 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE = 'GET_DATA_FAILURE',
  RESET_DATA = 'RESET_DATA',
}

export default actionTypeKeys
